-- Gradebook column groups.
--
-- Until now, "which columns belong together" was not stored anywhere. The gradebook table
-- derived it at render time in the `groupedColumns` memo
-- (app/course/[course_id]/manage/gradebook/gradebookTable.tsx) by splitting `slug` on "-",
-- taking a prefix, and breaking the run wherever `sort_order` stopped being contiguous.
--
-- This migration makes a group a row. Membership is stored on the column, not recomputed.
--
-- Schema + RLS + backfill are one file because they are one change: the table is useless
-- without the policies, and a gradebook that comes out of this migration ungrouped is a
-- regression. Splitting them would let a deploy stop halfway in a state we never test.

-- ---------------------------------------------------------------------------
-- 1. Schema
-- ---------------------------------------------------------------------------

create table "public"."gradebook_column_groups" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "class_id" bigint not null,
    "gradebook_id" bigint not null,
    -- Stable identity for the group within its gradebook. Backfilled with the key the
    -- render-time heuristic used to synthesise ("quiz-4", "skill-6"). It is an opaque
    -- identifier, not a slug: the digit is a per-gradebook group counter, not a column
    -- number. Nothing parses it.
    "group_key" text not null,
    -- What the header shows. Deliberately NOT unique per gradebook: the grouping this
    -- migration reproduces contains two distinct groups both displaying "Quiz" (the
    -- `quiz-3` column was deleted, which split the run in two). A uniqueness constraint
    -- here would make the correct answer impossible to store.
    "name" text not null,
    -- Left-to-right position: the smallest sort_order among the group's columns.
    "sort_order" integer not null
);

alter table "public"."gradebook_column_groups" add constraint "gradebook_column_groups_pkey"
    primary key ("id");

-- One group per key per gradebook.
create unique index "gradebook_column_groups_gradebook_id_group_key_key"
    on "public"."gradebook_column_groups" ("gradebook_id", "group_key");

-- Exists only to be the target of the composite foreign key from gradebook_columns below.
-- It is what makes "a column in another gradebook's group" unrepresentable rather than
-- merely unlikely.
create unique index "gradebook_column_groups_id_gradebook_id_key"
    on "public"."gradebook_column_groups" ("id", "gradebook_id");

-- Same trick one level up: pins a group's class_id to its gradebook's class_id, so a group
-- cannot claim to belong to a class its gradebook does not belong to.
create unique index if not exists "gradebooks_id_class_id_key"
    on "public"."gradebooks" ("id", "class_id");

alter table "public"."gradebook_column_groups" add constraint "gradebook_column_groups_gradebook_id_class_id_fkey"
    foreign key ("gradebook_id", "class_id")
    references "public"."gradebooks" ("id", "class_id") on delete cascade;

alter table "public"."gradebook_column_groups" add constraint "gradebook_column_groups_class_id_fkey"
    foreign key ("class_id") references "public"."classes" ("id") on delete cascade;

-- The RLS predicates below are both class_id-scoped; without this every policy check is a
-- sequential scan once more than one course exists.
create index "idx_gradebook_column_groups_class_id"
    on "public"."gradebook_column_groups" ("class_id");

create index "idx_gradebook_column_groups_gradebook_id"
    on "public"."gradebook_column_groups" ("gradebook_id");

-- Membership lives on the column: many columns to one group.
-- Nullable on purpose. A column created after this migration has no group until something
-- assigns one, and a NOT NULL here would mean either inventing a group at insert time (the
-- slug heuristic again, which is what we are removing) or breaking column creation.
alter table "public"."gradebook_columns" add column "group_id" bigint;

-- The composite key, not a plain FK on group_id alone: it forces the column's own
-- gradebook_id to equal the group's. A column can only ever point at a group in its own
-- gradebook. NULL group_id skips the check (MATCH SIMPLE), which is what we want.
-- SET NULL names group_id alone: a bare SET NULL on a composite key would also null the
-- column's gradebook_id, which is NOT NULL, so deleting any group would fail.
alter table "public"."gradebook_columns" add constraint "gradebook_columns_group_id_gradebook_id_fkey"
    foreign key ("group_id", "gradebook_id")
    references "public"."gradebook_column_groups" ("id", "gradebook_id") on delete set null ("group_id");

create index "idx_gradebook_columns_group_id"
    on "public"."gradebook_columns" ("group_id");

-- ---------------------------------------------------------------------------
-- 2. Grants and RLS
--
-- Mirrors gradebook_columns exactly: same helper functions, same roles, same read/write
-- split. Instructors get everything, anyone in the class can read. Nobody sees another
-- course's groups. See 20250614231720_gradebook.sql.
-- ---------------------------------------------------------------------------

grant delete on table "public"."gradebook_column_groups" to "anon";
grant insert on table "public"."gradebook_column_groups" to "anon";
grant references on table "public"."gradebook_column_groups" to "anon";
grant select on table "public"."gradebook_column_groups" to "anon";
grant trigger on table "public"."gradebook_column_groups" to "anon";
grant truncate on table "public"."gradebook_column_groups" to "anon";
grant update on table "public"."gradebook_column_groups" to "anon";

grant delete on table "public"."gradebook_column_groups" to "authenticated";
grant insert on table "public"."gradebook_column_groups" to "authenticated";
grant references on table "public"."gradebook_column_groups" to "authenticated";
grant select on table "public"."gradebook_column_groups" to "authenticated";
grant trigger on table "public"."gradebook_column_groups" to "authenticated";
grant truncate on table "public"."gradebook_column_groups" to "authenticated";
grant update on table "public"."gradebook_column_groups" to "authenticated";

grant delete on table "public"."gradebook_column_groups" to "service_role";
grant insert on table "public"."gradebook_column_groups" to "service_role";
grant references on table "public"."gradebook_column_groups" to "service_role";
grant select on table "public"."gradebook_column_groups" to "service_role";
grant trigger on table "public"."gradebook_column_groups" to "service_role";
grant truncate on table "public"."gradebook_column_groups" to "service_role";
grant update on table "public"."gradebook_column_groups" to "service_role";

alter table "public"."gradebook_column_groups" enable row level security;

create policy "instructors CRUD"
on "public"."gradebook_column_groups"
as permissive
for all
to public
using (authorizeforclassinstructor(class_id));

create policy "everyone in class can view"
on "public"."gradebook_column_groups"
as permissive
for select
to public
using (authorizeforclass(class_id));

-- ---------------------------------------------------------------------------
-- 3. Recovery of the implicit naming convention  --  ONE TIME PER GRADEBOOK
--
-- This function is the single place the slug heuristic is allowed to run, and it is a
-- recovery step, not a rule. The grouping instructors have been looking at was never
-- recorded anywhere, so the only surviving source for it is the slugs themselves. It reads
-- them once per gradebook and writes down what it finds. After that the convention stops
-- being load-bearing: nothing derives a group from a slug again.
--
-- There is deliberately NO trigger, NO view and NO generated column keeping groups in sync
-- with slugs. A group is whatever the rows say it is. This function only ever touches a
-- gradebook in which *nothing* is grouped yet, so it cannot silently re-group a gradebook
-- someone has since organised by hand -- re-running it is a no-op, not a reset.
--
-- It is called twice in the project's lifetime: once by the statement at the bottom of this
-- migration, for the gradebooks that already exist; and once per seeded class by
-- scripts/DatabaseSeedingUtils.ts, because `supabase db reset` replays migrations against an
-- empty database and the seeder then creates gradebooks that never existed when the backfill
-- above ran. Execute is granted to service_role only -- it is not a runtime API.
--
-- It follows gradebookTable.tsx:2556-2615 (a run of adjacent columns with the same slug
-- prefix is a group), except where that rule demonstrably gets the seeded cs4535 gradebook
-- wrong. Each fix is marked FIX below:
--
--   FIX 1  A gap in sort_order no longer ends a group. The memo required sort_order to go up
--          by exactly 1, so deleting quiz-3 split quiz-1,quiz-2 | quiz-4,quiz-5 into two
--          groups, both labelled "Quiz". A group is now a run of *adjacent* columns: a deleted
--          column leaves no hole.
--   FIX 2  Group names come from the columns' names, not a slug fragment. The memo
--          capitalised the slug's first segment, giving "Ai" for "AI Usage Log 1/2" and
--          "Average.hw" for "Average HW". The name is now the words every member's name starts
--          with, minus a trailing number ("AI Usage Log", "Skill", "Quiz"), falling back to the
--          old label only when the members share no leading word.
--   FIX 3  A group of one is named after its column. The memo named `meets-expectations`
--          "Meets", `does-not-meet-expectations` "Does" and `assignment-final` (Final Project)
--          "Assignment". The table draws no header for a singleton, but the name is what the
--          Column Groups dialog lists and what the group is called once a column joins it.
--   FIX 4  `assignment-<word>` with two slug parts keys as "assignment-<word>", not
--          "assignment", when <word> is not a number. Otherwise `assignment-final` merges into
--          any adjacent column whose slug starts "assignment-" with two parts.
--
-- Unchanged on purpose: a slug with no "-" groups under the whole slug, "Other" is reached
-- only by an empty slug, and every column gets a group.
--
-- Unclassifiable rows: there are none, and that is the stated policy. Every column gets a
-- group, singletons included -- that is what the heuristic does, and the table simply
-- declines to draw a header for a group of one. Recording singletons as NULL instead would
-- lose FIX 3's name and make "which group is this column in" a two-case question.
--
-- Ordering: columns are walked by (coalesce(sort_order,0), id). The memo sorts on
-- `sort_order ?? 0` with a stable sort, so its tiebreak is whatever order the client happened
-- to fetch rows in, which is not reproducible in SQL. `id` is an explicit, deterministic
-- stand-in. No seeded gradebook has a tie, so it cannot change the result here; on production
-- data it makes the outcome defined rather than incidental.
-- ---------------------------------------------------------------------------

-- FIX 2 / FIX 3: a group's name from its columns' names. The words every name starts with
-- (compared case-insensitively, kept in the first column's casing), minus trailing number
-- tokens like "3" or "#12". NULL when nothing is shared, and the caller falls back to the
-- slug-derived label.
--   {"AI Usage Log 1", "AI Usage Log 2"}     -> "AI Usage Log"
--   {"Skill #1", ..., "Skill #12"}           -> "Skill"
--   {"Lab 1 (Group)", "Lab 2", "Lab 3"}      -> "Lab"
--   {"Final Project"}                        -> "Final Project"
--   {"Labs (drop lowest 2)"}                 -> "Labs (drop lowest 2)"
create or replace function public.gradebook_group_name_from_columns(p_names text[])
returns text
language plpgsql
immutable
set search_path to 'public', 'pg_temp'
as $function$
declare
    v_words text[];
    v_other text[];
    v_n integer;
    v_i integer;
    v_name text;
begin
    if p_names is null or coalesce(array_length(p_names, 1), 0) = 0 or p_names[1] is null then
        return null;
    end if;
    v_words := regexp_split_to_array(btrim(p_names[1]), '\s+');
    v_n := coalesce(array_length(v_words, 1), 0);
    foreach v_name in array p_names loop
        v_other := regexp_split_to_array(btrim(coalesce(v_name, '')), '\s+');
        v_i := 0;
        while v_i < least(v_n, coalesce(array_length(v_other, 1), 0))
              and lower(v_words[v_i + 1]) = lower(v_other[v_i + 1]) loop
            v_i := v_i + 1;
        end loop;
        v_n := v_i;
    end loop;
    while v_n > 0 and v_words[v_n] ~ '^#?[0-9]+$' loop
        v_n := v_n - 1;
    end loop;
    if v_n = 0 or btrim(array_to_string(v_words[1:v_n], ' ')) = '' then
        return null;
    end if;
    return array_to_string(v_words[1:v_n], ' ');
end;
$function$;

create or replace function public.backfill_gradebook_column_groups(p_class_id bigint default null)
returns integer
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
    v_groups_created integer;
begin
    with targets as (
        -- Only gradebooks in which nothing is grouped yet.
        select c.gradebook_id
        from public.gradebook_columns c
        where p_class_id is null or c.class_id = p_class_id
        group by c.gradebook_id
        having count(c.group_id) = 0
    ),
    walked as (
        select
            c.id,
            c.class_id,
            c.gradebook_id,
            c.name as column_name,
            case
                when split_part(c.slug, '-', 1) = 'assignment'
                     and array_length(string_to_array(c.slug, '-'), 1) >= 3
                then split_part(c.slug, '-', 1) || '-' || split_part(c.slug, '-', 2)
                -- FIX 4
                when split_part(c.slug, '-', 1) = 'assignment'
                     and array_length(string_to_array(c.slug, '-'), 1) = 2
                     and split_part(c.slug, '-', 2) !~ '^[0-9]+$'
                then c.slug
                when split_part(c.slug, '-', 1) = '' then 'other'
                else split_part(c.slug, '-', 1)
            end as base_group_name,
            coalesce(c.sort_order, 0) as effective_sort_order,
            lag(coalesce(c.sort_order, 0)) over w as prev_sort_order,
            lag(
                case
                    when split_part(c.slug, '-', 1) = 'assignment'
                         and array_length(string_to_array(c.slug, '-'), 1) >= 3
                    then split_part(c.slug, '-', 1) || '-' || split_part(c.slug, '-', 2)
                    when split_part(c.slug, '-', 1) = 'assignment'
                         and array_length(string_to_array(c.slug, '-'), 1) = 2
                         and split_part(c.slug, '-', 2) !~ '^[0-9]+$'
                    then c.slug
                    when split_part(c.slug, '-', 1) = '' then 'other'
                    else split_part(c.slug, '-', 1)
                end
            ) over w as prev_base_group_name
        from public.gradebook_columns c
        join targets t on t.gradebook_id = c.gradebook_id
        window w as (partition by c.gradebook_id order by coalesce(c.sort_order, 0), c.id)
    ),
    flagged as (
        -- A new group starts on the first column of a gradebook or on a change of base group
        -- name. The memo also started one on any break in sort_order contiguity (FIX 1).
        select
            walked.*,
            case
                when prev_sort_order is null then 1
                when base_group_name <> prev_base_group_name then 1
                else 0
            end as starts_group
        from walked
    ),
    numbered as (
        -- The memo's `currentGroupIndex`: a per-gradebook counter that increments on every
        -- new group and is never reset, which is what makes the keys unique per gradebook.
        select
            flagged.*,
            sum(starts_group) over (
                partition by gradebook_id
                order by effective_sort_order, id
                rows between unbounded preceding and current row
            ) as group_index
        from flagged
    ),
    keyed as (
        select
            numbered.*,
            base_group_name || '-' || group_index::text as group_key,
            case
                when base_group_name = 'other' then 'Other'
                -- charAt(0).toUpperCase() + slice(1): only the first character changes.
                -- initcap() would also lower-case the rest, which the memo does not do.
                when base_group_name like 'assignment-%'
                    then upper(left(split_part(base_group_name, '-', 2), 1))
                         || substr(split_part(base_group_name, '-', 2), 2)
                else upper(left(base_group_name, 1)) || substr(base_group_name, 2)
            end as display_name
        from numbered
    ),
    inserted as (
        insert into public.gradebook_column_groups (class_id, gradebook_id, group_key, name, sort_order)
        select
            min(class_id),
            gradebook_id,
            group_key,
            coalesce(
                public.gradebook_group_name_from_columns(array_agg(column_name order by effective_sort_order, id)),
                min(display_name)
            ),
            min(effective_sort_order)
        from keyed
        group by gradebook_id, group_key
        returning id, gradebook_id, group_key
    ),
    assigned as (
        update public.gradebook_columns c
        set group_id = inserted.id
        from keyed, inserted
        where keyed.id = c.id
          and inserted.gradebook_id = keyed.gradebook_id
          and inserted.group_key = keyed.group_key
        returning c.id
    )
    select count(*) into v_groups_created from inserted;

    return coalesce(v_groups_created, 0);
end;
$function$;

comment on function public.backfill_gradebook_column_groups(bigint) is
    'One-time recovery of the implicit slug-prefix grouping convention, for gradebooks that have no groups yet. Called by the migration that introduced gradebook_column_groups and by the seeder. Not a runtime API and not kept in sync with slugs: after it runs, a group is whatever the rows say it is.';

revoke all on function public.backfill_gradebook_column_groups(bigint) from public;
revoke all on function public.backfill_gradebook_column_groups(bigint) from anon;
revoke all on function public.backfill_gradebook_column_groups(bigint) from authenticated;
grant execute on function public.backfill_gradebook_column_groups(bigint) to service_role;

-- The one-time statement, for gradebooks that exist at the moment this migration runs. On a
-- `supabase db reset` there are none, and the seeder calls the same function afterwards.
select public.backfill_gradebook_column_groups();

comment on table "public"."gradebook_column_groups" is
    'Stored grouping for gradebook columns. Recovered once from the slug-prefix convention the gradebook table used to recompute at render time; nothing derives a group from a slug after that.';

comment on column "public"."gradebook_columns"."group_id" is
    'The column''s group. NULL means ungrouped; the gradebook table renders such a column as a group of one.';
